### ISSUE TITLE
The best way to describe unavailable values.

### ISSUE THREAD

**Issue by xiki-tempula** [samplchallenges/SAMPL8#31]
Sorry for raising this question this late.
For the SAMPL8 physical_properties pKa challenge, we are asked to give the RELATIVE FREE ENERGY PREDICTIONS between the reference microstate to every other microstate.
In the ideal state, one could report all the RBFE for all microstates. However, I found that I got some errors in some calculations, which I might not have time to fix. I wonder what is the best way to proceed.

Can I submit it as

SAMPL8-1_micro000,SAMPL8-1_micro003,-1,NaN,0,0 

to indicate that I'm not confident about this value?
Thank you.

**Comment by davidlmobley** [comment]
You don't have to submit the free energy relative to every other microstate, only relative to the microstates you believe are relevant. Any microstates which are omitted will be assumed to be predicted to be irrelevant.

For example, hypothetically, if you had states 0, 1, 2, and 3, and you submitted the free energies for 0->1 and 0->2 only, we would assume that you predict states 1 and 3 are not populated.

This is the only thing we are able to do with incomplete submissions, since translating relative free eneriges to titration curves requires estimating the populations of states; if you don't submit state free energies for some states, we can't estimate their populations and thus we can't include them in the titration.
